/**
 * A hand-made print DTO for the renderer tests (same shape the core returns): a Maharashtra B2B tax
 * invoice — Rice 10 × 50 @5% and Mixer 2 × 150 − 10% @18%, total ₹844.00 (round off +0.40).
 */
import { DEFAULT_CONFIG } from '../../../../shared/settings.ts';
import type { PrintLine, PrintVoucherData } from '../../../../shared/types/print.ts';

export function line(o: Partial<PrintLine> = {}): PrintLine {
  return {
    sl: 1,
    kind: 'item',
    name: 'Rice Bag',
    description: null,
    hsnSac: '1006',
    batch: null,
    qty: 10,
    unit: 'Nos',
    qtyDecimals: 0,
    rate: 50,
    discountPct: 0,
    discount: 0,
    amount: 50000,
    taxableValue: 50000,
    taxability: 'taxable',
    gstRate: 5,
    cessRate: 0,
    cgst: 1250,
    sgst: 1250,
    igst: 0,
    cess: 0,
    tax: 2500,
    taxPayable: true,
    absorbed: false,
    reverseCharge: false,
    section: null,
    ...o,
  };
}

export function sampleDoc(o: Partial<PrintVoucherData> = {}): PrintVoucherData {
  const lines = [
    line(),
    line({ sl: 2, name: 'Mixer Grinder', hsnSac: '8509', qty: 2, rate: 150, discountPct: 10, discount: 3000, amount: 27000, taxableValue: 27000, gstRate: 18, cgst: 2430, sgst: 2430, tax: 4860 }),
  ];
  return {
    id: 7,
    sample: false,
    layout: 'invoice',
    kind: 'tax_invoice',
    baseType: 'sales',
    voucherTypeId: 5,
    voucherTypeName: 'Sales',
    title: 'Tax Invoice',
    endorsement: null,
    notes: [],
    number: 'INV/12',
    date: '2026-04-15',
    referenceNo: null,
    referenceDate: null,
    status: { cancelled: false, cancelReason: null, optional: false, postDated: false },
    company: {
      name: 'Test Traders',
      displayName: 'Test Traders',
      address: '12 MG Road\nFort',
      pincode: '400001',
      stateCode: '27',
      stateName: 'Maharashtra',
      country: 'India',
      gstin: '27AAPFU0939F1ZV',
      pan: 'AAPFU0939F',
      registrationType: null,
      phone: '022 1234 5678',
      email: null,
      website: null,
      cin: null,
      gstRegistrationType: 'regular',
      logo: null,
    },
    partyLabel: 'Buyer (Bill to)',
    party: {
      name: 'Acme Traders',
      address: 'Shop 4, Market Yard',
      pincode: '411037',
      stateCode: '27',
      stateName: 'Maharashtra',
      country: 'India',
      gstin: '27AAAPA0001A1Z6',
      pan: 'AAAPA0001A',
      registrationType: 'regular',
      phone: null,
      email: null,
    },
    consigneeLabel: 'Consignee (Ship to)',
    consignee: null,
    consigneeSameAsParty: true,
    placeOfSupply: { code: '27', name: 'Maharashtra', label: '27-Maharashtra' },
    reverseCharge: false,
    gst: { showTax: true, taxMode: 'cgst_sgst', interState: false, sgstLabel: 'SGST', nature: 'b2b' },
    lines,
    charges: [],
    taxByRate: [],
    taxByHsn: [],
    totals: {
      qty: 12,
      unit: 'Nos',
      qtyDecimals: 0,
      discount: 3000,
      taxable: 77000,
      cgst: 3680,
      sgst: 3680,
      igst: 0,
      cess: 0,
      tax: 7360,
      reverseChargeTax: 0,
      charges: 0,
      roundOff: 40,
      grandTotal: 84400,
    },
    amountInWords: 'Rupees Eight Hundred Forty Four Only',
    taxInWords: 'Rupees Seventy Three and Sixty Paise Only',
    entries: [],
    narration: null,
    originalInvoice: null,
    references: [],
    einvoice: null,
    ewayBill: null,
    bank: null,
    upi: null,
    declaration: DEFAULT_CONFIG.invoice.declaration,
    terms: null,
    signatoryLabel: 'Authorised Signatory',
    copyLabels: { original: 'Original for Recipient', duplicate: 'Duplicate for Transporter', triplicate: 'Triplicate for Supplier' },
    options: { ...DEFAULT_CONFIG.invoice, copies: ['original', 'duplicate'] },
    defaultTemplate: 'modern',
    navigation: { prevId: null, nextId: null },
    warnings: [],
    ...o,
  };
}
